name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR'
version-resolver:
  major:
    labels:
      - 'version:major'
  minor:
    labels:
      - 'version:minor'
  patch:
    labels:
      - 'version:patch'
  default: patch
template: |
  ## Changes
  
  $CHANGES
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🔺 Improvements'
    label: 'improvement'

